### ISSUE TITLE
Working on MacBookPro16,1

### ISSUE THREAD

**Issue by ceinem** [mikeeq/mbp-fedora#15] opened 2020-02-02 22:20 UTC
Hi, 
I have the 16inch MacBook Pro and tried to install Fedora using your amazing work. 
I managed to get it booting from the usb drive, it did a check of the boot medium, showed the fedora logo for a few seconds and then the screen went blank. The Touch Bar started showing stuff (which I thought was a good sign), but nothing else would happen. I restarted the computer after a few minutes and tried again, but got stuck at the same point. 

Any advice?

Thanks a lot!

**Comment by jamlam** [comment] 2020-02-09 10:45
I'm typing this from an MBP 16,1, you can boot using Troubleshooting-> Safe Graphics mode from the GRUB menu. Everything seems to work fine apart from the WiFi; as Catalina FW doesn't work when extracted and the MBP 16,1 isn't supported by Mojave there's no firmware available for the chip in these laptops (BCM4634 - Bali). Hopefully someone will find something usable for this soon!

**Comment by jamlam** [comment] 2020-02-09 10:45
Bluetooth networking works fine though so there is a workaround.

**Comment by jamlam** [comment] 2020-02-10 07:49
After a little experimentation here the works/doesn't work list for the 2019 MBP 16 is as below

Working: 
Trackpad (although detected as mouse so no multi-touch or right click atm)
Keyboard (no Fn Keys)
Touchbar
Display
Bluetooth (complains about missing firmware but seems to work)
Camera

Not Working:
Wifi (lacks firmware)
Sound (device detected but no output from speakers)

**Comment by FabriceColin** [comment] 2020-02-13 17:38
I am having the same experience as jamlam on my own 16 inch MBP.

Regarding Wifi, I have followed the instructions at https://github.com/mikeeq/mbp-fedora-kernel/#working-with-mbp-fedora-kernel and have these files in /lib/firmware/brcm
-rw-r--r--. 1 root root  762279 Feb 11 21:15  brcmfmac4364-pcie.bin
-rw-r--r--. 1 root root   31538 Feb 11 21:15  brcmfmac4364-pcie.clm_blob
-rw-r--r--. 1 root root   12841 Feb 11 21:17 'brcmfmac4364-pcie.Apple Inc.-MacBookPro15,2.txt'
-rw-r--r--. 1 root root   12841 Feb 11 21:16 'brcmfmac4364-pcie.Apple Inc.-MacBookPro16,1.txt'
(it seemed to make sense to have an extra copy of the txt file with a name referring MacBookPro16,1 :-) )

**Comment by jamlam** [comment] 2020-02-13 20:20
I've found that moving to Fedora Mainline kernel 5.6 removes the need for nomodeset, and the patches all still apply. Fn keys work now as well, but no Bluetooth/WiFi or trackpad other than single-finger left click. I think that the hid-apple patch lacks the right DevIDs for the trackpad in the 16,1 so it's getting picked up as a Generic USB Mouse. I've tried adding a few things in there but no luck yet.

**Comment by luc3004** [comment] 2020-02-15 13:16
Hi jamlam, - am not interested in Bluetooth/Wifi at thsi point, need a virtualization engine. tried Fedora LVM few weeks ago did not work.  please can you provide installation instructions/links
MBP16,1 8 core i9 NVMExpress. thanks. !

**Comment by jamlam** [comment] 2020-02-16 14:00
Hi, just use mikeeq's gist instructions and ISO. I didn't do anything special apart from select Safe Graphics Mode from the GRUB menu. If you're just using it as a virtualization box I wouldn't bother with the 5.6 version, the only thing it realy gains you is 3D Accel which won't be much use on a VM host. That said, I really wouldn't use this for anything serious yet! I understand that LVM parttion isn't working yet either so only standard partitions for now.

**Comment by mikeeq** [comment] 2020-02-26 11:53
@jamlam @FabriceColin @luc3004 is it working for you now on MBP16,1, can I close this issue?

**Comment by jamlam** [comment] 2020-02-26 12:15
There are a few things we need before we can say it's working for the 2019 MBP I think.
 - Move to 5.6.x to fix nomodeset requirement
 - Fix Wifi - Thanks to a suggestion from Aunali1 I've grabbed the firmware from the Bootcamp drivers. It gets further now but I think the rambase address is incorrect. I'm working on this now (by trial and error) so if I find anything I'll post it here.

I've also updated the wifi patch to work against 5.6, I've attached that here.
[wifi.patch.txt](https://github.com/mikeeq/mbp-fedora/files/4255588/wifi.patch.txt)

**Comment by FabriceColin** [comment] 2020-02-26 12:57
Beside Wifi, the other issue I have on MPB 16,1 is that intermittently keyboard and trackpad are not working at all, I need to plug an external USB keyboard.

**Comment by rieske** [comment] 2020-03-10 14:47
I am on MBP 16,1 as well.

What still does not work for me:
- wifi (haven't yet played with rambase addresses, just tried different combinations of firmware, including one from bootcamp - no luck)
- audio output (headphones output works fine)
- built-in microphone as well as headphones microphone - shows some signs of life, but the volume  of recorded audio is too low to be usable

Another thing that I haven't yet understood the cause of:
With https://github.com/mikeeq/mbp-fedora/releases/tag/v5.4.20-f31 build, I can boot from usb fine and can use HDMI - both for external monitor and audio. For later builds, however, I have to use the `Troubleshooting-> Safe Graphics mode` to boot from usb and then HDMI is unusable and the built-in monitor is shown as `Unknown Monitor`.
Same after installing - https://github.com/mikeeq/mbp-fedora/releases/tag/v5.4.20-f31 build works, later ones - no HDMI/unknown monitor.
Sorry for my lack of deeper understanding on this matter.


Otherwise, this is awesome work - thank you very much for the effort!

**Comment by kevineinarsson** [comment] 2020-03-10 14:57
@rieske does your laptop have a discrete AMD GPU? For modesetting to work for me I needed to use kernel 5.6 (mainline) because of some changes to the amdgpu module. I used (this)[https://github.com/jamlam/mbp2019-5.6-patches] set of patches without 2001-Revert... (issue open to test if it's needed) and compiled 5.6-rc5 which solved my issues.

**Comment by rieske** [comment] 2020-03-11 17:13
@kevineinarsson thanks!
Yes, mine has a discrete AMD GPU. I managed to compile 5.6-rc5 kernel with https://github.com/mcmrarm/mbp2018-bridge-drv/ and https://github.com/roadrunner2/macbook12-spi-driver/tree/mbp15 and the patches that you linked to applied. HDMI worked with it, as well as keyboard/touchpad/touchbar/bluetooth, however, the system became very unstable overall. I guess I will play with it more when time permits. Otherwise, `v5.4.20-f31` seems to work pretty fine with an external wifi dongle for now.

I also tried fixing audio using your [gist](https://gist.github.com/kevineinarsson/8e5e92664f97508277fefef1b8015fba) - it really shows that it is a configuration issue from here on and it can be made to work both with `v5.4.20-f31` build and with `5.6`. I still need to figure the input. An external webcam microphone works, but not the built-in one nor the one with headphones.

**Comment by mikeeq** [comment] 2020-04-20 08:33
Can anyone with MBP 16" test a new build with v5.6.5 backed in?

**Comment by ceinem** [comment] 2020-04-23 22:12
I just tried the new build. Seems to install fine, no problems. I'm not sure if I missed something, but it set up the psrtition layout by itself, I only had to specify some empty harddrive space. Kernel update script is running right now, will report later. So far still no luck with the wifi.

**Comment by FabriceColin** [comment] 2020-04-25 08:07
I installed 5.6.5 with dnf on a system installed with the previous ISO, don't see the apple-ib* kernel modules that exist for 5.4.10-200.mbp. Therefore keyboard and trackpad are not functional. What am I missing?

**Comment by ceinem** [comment] 2020-04-26 23:44
@FabriceColin you probably have to use the update commands for the customized kernel from [here](https://github.com/mikeeq/mbp-fedora-kernel#how-to-update-kernel-mbp)

**Comment by FabriceColin** [comment] 2020-04-27 07:25
Indeed, that's what I needed to do. Thanks!

**Comment by mikeeq** [comment] 2020-04-27 08:13
Sorry guys, I wasn't using my computer during the weekend. Thanks for help @ceinem, yes that's true you need to run the update from that script, because there are multiple settings which you need to cover after the first boot and it wasn't possible to do it in the kickstart. Also I was trying to include external modules in the kernel itself but I couldn't make it working, so it's done via bash script as for now. 

WiFi on newer Macs will be really hard to fix, because we are dependent on the Broadcom firmware which is delivered with MacOS and newer versions of that firmware don't even work on older T2 Macs (i.e. 2018).

**Comment by luc3004** [comment] 2020-04-27 11:11
Macbook 16,1: AMD Radeon Pro 5500M(PCIe), Intel UHD Graphics 630 (buit-in), NVMExpress/4TB - using mostly for KVM virtualization  (16vCPU, 64GB mem)

Have just installed 5.6.5-300, LVM,  the problems so far:

- it reboots sometimes 
-after lid is closed, someties screen remains black - still accessible from remote via ssh
- ventilators work intensively even if  the load is not high on vCPU (all vCPU under10%, one CPU reaches 30-40%)  
- errors below multiple times in journalctl 
drm:mod_hdcp_add_display_topology [amdgpu]] *ERROR* Failed to add display topology, DTM TA is not initialized

**Comment by mikeeq** [comment] 2020-04-27 11:51
@luc3004 have you checked CPU temps when fans speed bumped up? 
```
dnf install lm_sensors
sensors
```

**Comment by luc3004** [comment] 2020-04-27 16:21
__________________________________________________
sar -u 1 3
Linux 5.6.5-300.mbp.fc31.x86_64 (mac20) 	04/27/2020 	_x86_64_	(16 CPU)

06:09:20 PM     CPU     %user     %nice   %system   %iowait    %steal     %idle
06:09:21 PM     all      4.30      0.00      1.62      0.00      0.00     94.08
06:09:22 PM     all      4.18      0.00      1.37      0.00      0.00     94.39
06:09:23 PM     all      4.35      0.00      1.68      0.00      0.00     93.84
Average:        all      4.28      0.00      1.56      0.00      0.00     94.12
_________________________________________________________

applesmc-acpi-0
Adapter: ACPI interface
fan1:        4845 RPM  (min = 1836 RPM, max = 5616 RPM)
fan2:        4476 RPM  (min = 1700 RPM, max = 5200 RPM)
TA0V:         +29.8°C  
TB0T:         +33.5°C  
TB1T:         +32.2°C  
TB2T:         +33.5°C  
TC0E:         +71.8°C  
TC0F:         +73.2°C  
TC0P:         +67.2°C  
TC0T:          +0.0°C  
TC1C:         +70.0°C  
TC2C:         +69.0°C  
TC3C:         +68.0°C  
TC4C:         +67.0°C  
TC5C:         +66.0°C  
TC6C:         +69.0°C  
TC7C:         +69.0°C  
TC8C:         +72.0°C  
TCGC:         +66.0°C  
TCMX:         +72.2°C  
TCSA:         +69.0°C  
TCXC:         +72.2°C  
TF0S:          +6.8°C  
TG0P:         +62.8°C  
TG1P:         +60.5°C  
TGDD:         +66.0°C  
TGDE:         +57.0°C  
TGDF:         +66.8°C  
TGDT:          -0.2°C  
TGVF:         +64.2°C  
TGVP:         +64.2°C  
TH0F:         +38.5°C  
TH0X:         +38.5°C  
TH0a:         +34.2°C  
TH0b:         +37.0°C  
TH1a:         +34.2°C  
TH1b:         +38.5°C  
TM0P:         +54.2°C  
TPCD:         +58.0°C  
TTLD:         +47.5°C  
TTRD:         +49.8°C  
TW0P:         +53.8°C  
TaLC:         +42.2°C  
TaRC:         +44.5°C  
Th1H:         +65.0°C  
Th2H:         +60.2°C  
Tm0P:         +63.8°C  
Ts0P:         +34.8°C  
Ts0S:         +44.2°C  
Ts1P:         +31.8°C  
Ts1S:         +44.2°C  
Ts2S:         +44.5°C  

BAT0-virtual-0
Adapter: Virtual device
temp1:        +33.9°C  

nvme-pci-0400
Adapter: PCI adapter
Composite:    +33.9°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +72.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +70.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +71.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +68.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +69.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +68.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +69.0°C  (high = +100.0°C, crit = +100.0°C)
Core 6:        +70.0°C  (high = +100.0°C, crit = +100.0°C)
Core 7:        +72.0°C  (high = +100.0°C, crit = +100.0°C)

BAT0-acpi-0
Adapter: ACPI interface
in0:          +12.82 V  
temp ambient:  +33.9°C  
curr1:         +0.00 A  (avg =  +0.00 A)

pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:        +58.0°C  

amdgpu-pci-0300
Adapter: PCI adapter
vddgfx:       +0.01 V  
fan1:           0 RPM  (min =    0 RPM, max = 4950 RPM)
edge:         +66.0°C  (crit = +113.0°C, hyst = -273.1°C)
                       (emerg = +99.0°C)
junction:     +67.0°C  (crit = +99.0°C, hyst = -273.1°C)
                       (emerg = +99.0°C)
mem:           +0.0°C  (crit = +99.0°C, hyst = -273.1°C)
                       (emerg = +99.0°C)
power1:       14.00 W  (cap =  50.00 W)

**Comment by luc3004** [comment] 2020-05-06 08:24
update: if i stop display-manager (gdm, kdm, ...) then i can run couple of VMs without issues. 
As i use this laptop mostly for virtualization, this is ok for now.

One issue which appeared lately: the laptop keyboard/mouse are not accessible. Haven'T had time to investigate

**Comment by rotorek** [comment] 2021-01-21 17:13
I've just tried to install v5.7-f32 on MacBookPro16,1 (2019).  It boots ok, however internal keyboard and touchpad are not working. I see that bce module is loaded, however dmesg is full of errors with bce, like "bce_vhci_urb_dequeue 81".
When I try to run "Install to Hard-Disk", then nothing happens and after approx 5s the app shuts itself down everytime. Other apps like Firefox work just fine.

I tried to start anaconda from command line -- it took around 10 minutes for the app to start and display the installer, then it became unresponsive during "Setting up installation source..." phase.

I'm attaching anaconda logs, boot.log, dmesg, lsmod and a screenshot here:
[Archive.zip](https://github.com/mikeeq/mbp-fedora/files/5850861/Archive.zip)

Note. Bce module worked just fine on the same hardware in recent OpenSuse Tumbleweed (in Dec 2020) -- however I'm not sure which kernel it was.

**Closed** 2021-06-23 14:23 UTC
